#!/usr/bin/env python3
"""Generate docker-compose.yml with a given number of Slurm compute node services.

Compose's --scale/deploy.replicas can't give each replica a unique hostname or
env var, which Slurm nodes need (distinct NodeName/SLURM_NODENAME). Rather than
work around that at runtime, this script generates one explicit service per
node, matching the NodeName=slurmnode[1-10] range configured in slurm.conf.

Usage:
    ./generate-compose.py [--nodes N] [--output FILE]
"""
import argparse

HEADER = """# Generated by generate-compose.py --nodes {nodes}. Do not hand-edit the
# slurmnode service blocks below; re-run the script to change the node count.
x-node-common: &node-common
  build:
    context: ./node
    args:
      UBUNTU_BASE: ${{UBUNTU_BASE}}
  image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-node:${{IMAGE_TAG}}
  shm_size: '4g'
  user: admin
  volumes:
    - shared-vol:/home/admin
  depends_on:
    slurmmaster:
      condition: service_started
    slurmfrontend:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=no", "admin@localhost", "hostname"]
    interval: 2s
    timeout: 2s
    retries: 10
    start_period: 5s

services:
  slurmfrontend:
    build:
      context: ./frontend
      args:
        UBUNTU_BASE: ${{UBUNTU_BASE}}
    image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-frontend:${{IMAGE_TAG}}
    container_name: ${{CLUSTER_NAME}}-frontend
    shm_size: '4g'
    hostname: slurmfrontend
    user: admin
    volumes:
      - shared-vol:/home/admin
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ssh-ready"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s
  slurmmaster:
    build:
      context: ./master
      args:
        UBUNTU_BASE: ${{UBUNTU_BASE}}
    image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-master:${{IMAGE_TAG}}
    container_name: ${{CLUSTER_NAME}}-master
    shm_size: '4g'
    hostname: slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
    environment:
      SLURM_CPUS_ON_NODE: ${{SLURM_CPUS_ON_NODE}}
    depends_on:
      slurmfrontend:
        condition: service_healthy
"""

NODE_TEMPLATE = """  slurmnode{n}:
    <<: *node-common
    container_name: ${{CLUSTER_NAME}}-node{n}
    hostname: slurmnode{n}
    environment:
      SLURM_NODENAME: slurmnode{n}
      SLURM_CPUS_ON_NODE: ${{SLURM_CPUS_ON_NODE}}
"""

FOOTER = """volumes:
  shared-vol:
"""

MAX_NODES = 10


def build_compose(nodes: int) -> str:
    if not 1 <= nodes <= MAX_NODES:
        raise ValueError(f"--nodes must be between 1 and {MAX_NODES} (slurm.conf defines NodeName=slurmnode[1-{MAX_NODES}])")
    parts = [HEADER.format(nodes=nodes)]
    parts.extend(NODE_TEMPLATE.format(n=i) for i in range(1, nodes + 1))
    parts.append(FOOTER)
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nodes", type=int, default=3, help="number of slurmnode services to generate (default: 3, max: %d)" % MAX_NODES)
    parser.add_argument("--output", default="docker-compose.yml", help="output file path (default: docker-compose.yml)")
    args = parser.parse_args()

    compose = build_compose(args.nodes)
    with open(args.output, "w") as f:
        f.write(compose)
    print(f"Wrote {args.output} with {args.nodes} node service(s).")


if __name__ == "__main__":
    main()
