name: PackageCleanup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        container: [frontend, master, node]     
    steps:
      -
        name: Remove untagged versions of dockerslurmcluster/slurm-${{ matrix.container }}
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerslurmcluster/slurm-${{ matrix.container }}'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
  cleanup-caches:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        container: [frontend, master, node]
        ubuntu: ['24.04', '26.04']
        arch: [amd64, arm64]
    steps:     
      -
        name: Remove untagged versions of dockerslurmcluster/${{ matrix.container }}-cache-${{ matrix.ubuntu }}-${{ matrix.arch }}
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerslurmcluster/${{ matrix.container }}-cache-${{ matrix.ubuntu }}-${{ matrix.arch }}'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
